### ISSUE TITLE
Extricate our Transport code and make it usable by the LibP2P community.

### ISSUE THREAD

**Issue by peterbraden** [hoprnet/hopr-connect#56]
### Goal
We have some interesting and useful code that allows libp2p to communicate across a NAT boundary, with some smart upgrade logic. At the moment this is tightly integrated with our code, and therefore isn't really usable by the larger libp2p community, but we would like to fix this by breaking it out into it's own module, and therefore allow the wider community to benefit from this, and also help us push it forward.

### Tasks
- [x] Move the transport code into a dedicated module or repository.
- [x] Come up with a better name for the transport strategy.
- [x] Document the code.
- [ ] Implement the libp2p transport test suite.
- [x] Generally just tidy up to the point that we are happy that this is of sufficient quality that it stands alone.

**Update**

dropping "Implement the libp2p transport test suite." because the test suite assumes different addressing and `libp2p-tcp`

**Update**

Created libp2p issue https://github.com/libp2p/js-libp2p/issues/870
